# Generated by Django 4.2.6 on 2023-10-20 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('beds_number', models.PositiveSmallIntegerField()),
                ('room_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='unique ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'available'), (1, 'booked'), (2, 'unavailable')], default=0, verbose_name='status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='base.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Room instance',
                'verbose_name_plural': 'Room instances',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booked_room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservetion', to='base.room', verbose_name='reservation')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
            },
        ),
    ]
