# Generated by Django 4.2.6 on 2023-10-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reservation_end_date_reservation_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
