# Generated by Django 4.2.6 on 2023-10-21 05:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', validators=[base.models.validate_room_image]),
        ),
    ]
