# Generated by Django 4.2.6 on 2023-10-21 05:36

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='base/room_images/', validators=[base.models.validate_room_image]),
        ),
    ]
